#!/bin/zsh
#
# .zshrc - Zsh file loaded on interactive shell sessions.
#

# Zsh options.
setopt extended_glob

# Source zstyles you might use with antidote.
[[ -e ${ZDOTDIR:-~}/.zstyles ]] && source ${ZDOTDIR:-~}/.zstyles

# Clone antidote if necessary.
[[ -d ${ZDOTDIR:-~}/.antidote ]] ||
  git clone https://github.com/mattmc3/antidote ${ZDOTDIR:-~}/.antidote

# Create an amazing Zsh config using antidote plugins.
source ${ZDOTDIR:-~}/.antidote/antidote.zsh
antidote load

# Launch theme starship
eval "$(starship init zsh)"

# Launch zoxide
export _ZO_FZF_OPTS="
  --border
  --height 40%
  --layout reverse
  --color=fg:#f8f8f2,bg:#282a36,hl:#bd93f9
  --color=fg+:#f8f8f2,bg+:#44475a,hl+:#bd93f9
  --color=info:#ffb86c,prompt:#50fa7b,pointer:#ff79c6
  --color=marker:#ff79c6,spinner:#ffb86c,header:#6272a4
  --preview 'echo {} | cut -f 2 | eza -1 -a --color=always --stdin'
"
eval "$(zoxide init zsh)"

# Force bindkey history-search-multi-word (override by zvm) 
function zvm_after_init() {
   zvm_bindkey viins '^R' history-search-multi-word
}

# Launch fzf
source <(fzf --zsh)

export FZF_DEFAULT_OPTS="
  --border
  --height 40%
  --layout reverse
  --color=fg:#f8f8f2,bg:#282a36,hl:#bd93f9
  --color=fg+:#f8f8f2,bg+:#44475a,hl+:#bd93f9
  --color=info:#ffb86c,prompt:#50fa7b,pointer:#ff79c6
  --color=marker:#ff79c6,spinner:#ffb86c,header:#6272a4
"
export FZF_CTRL_T_OPTS="
  --walker file,follow,hidden
  --walker-skip .git,node_modules,target
  --preview 'bat -n --color=always {}'
"
export FZF_ALT_C_OPTS="
  --walker-skip .git,node_modules,target
  --preview 'eza -1 -a --color=always {}'
"

# Chezmoi completion
source <(chezmoi completion zsh)